start.sh: 3: start.sh: source: not found
120.24.152.121 27020 mgdb8w34asdadat51!(( root {'j': True, 'w': 1}
MongoClient(host=['120.24.152.121:27020'], document_class=dict, tz_aware=False, connect=True, j=True, w=1)
Traceback (most recent call last):
  File "./main.py", line 144, in <module>
    ioloop.IOLoop.current().start()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 863, in start
    event_pairs = self._impl.poll(poll_timeout)
KeyboardInterrupt
start.sh: 3: start.sh: source: not found
start.sh: 3: start.sh: source: not found
